version: "3"

services:
  application:
    image: ${DOCKER_IMAGE}
    container_name: ilgijjan-server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/logs
    networks:
      - ilgijjan-net

  redis:
    image: redis:latest
    container_name: ilgijjan-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ilgijjan-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./logs:/var/log/ilgijjan
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: always
    networks:
      - ilgijjan-net

networks:
  ilgijjan-net:
    external: true