services:
  application-prod:
    image: ${DOCKER_IMAGE_PROD}
    container_name: ilgijjan-server-prod
    profiles: ["prod"]
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/logs
    networks:
      - ilgijjan-net

  application-dev:
    image: ${DOCKER_IMAGE_DEV}
    container_name: ilgijjan-server-dev
    profiles: ["dev"]
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./logs:/logs
    networks:
      - ilgijjan-net

  redis:
    image: redis:latest
    container_name: ilgijjan-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ilgijjan-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./logs:/var/log/ilgijjan
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: always
    networks:
      - ilgijjan-net

networks:
  ilgijjan-net:
    external: true